### ISSUE TITLE
Multiphase tutourials

### ISSUE THREAD

**Issue by Martin12312** [WENO-OF/WENOEXT#15]
It would be great to have tutorials of multiphase simulations.

**Comment by JanGaertner** [comment]
Do you have a specific use case in mind? E.g. interface tracking or momentum conservation?

A tutorial of a multiphase simulation or other types is not included as the WENO Scheme can be used for any divergence scheme you like.

At last, this topic would be better suited for a discussion and not an issue. You are welcome to raise questions and we can discuss design decisions, but the issues should be for bugs or problems with the code directly.

**Comment by Martin12312** [comment]
I am specifically interested in incompressible interfacial flows. Closing this and moving it to discussions.
